name: CITestApp
options:
  bundleIdPrefix: com.ci.test
  developmentLanguage: en
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

# packages:
  # Add Swift Package Manager dependencies here when needed
  # Example:
  # Alamofire:
  #   url: https://github.com/Alamofire/Alamofire
  #   majorVersion: 5.8.0

settings:
  base:
    # Swift version
    SWIFT_VERSION: "5.10"
    # Development settings
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "Apple Development"
    CODE_SIGN_STYLE: Automatic
    # Build settings
    ENABLE_BITCODE: false
    SUPPORTS_MACCATALYST: false
    # Warning settings
    SWIFT_TREAT_WARNINGS_AS_ERRORS: false
    GCC_TREAT_WARNINGS_AS_ERRORS: false
    # Other settings
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

targets:
  CITestApp:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - CITestApp
    resources:
      - CITestApp/Resources
    info:
      path: CITestApp/Info.plist
      properties:
        CFBundleDisplayName: CITestApp
        CFBundleIdentifier: com.ci.test.citestapp
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiredDeviceCapabilities:
          - armv7
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
    scheme:
      testTargets:
        - CITestAppTests
      gatherCoverageData: true
      coverageTargets:
        - CITestApp

  CITestAppTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - CITestAppTests
    dependencies:
      - target: CITestApp
    scheme:
      testTargets:
        - CITestAppTests
      gatherCoverageData: true

  CITestAppUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - CITestAppUITests
    dependencies:
      - target: CITestApp
    scheme:
      testTargets:
        - CITestAppUITests

schemes:
  CITestApp:
    build:
      targets:
        CITestApp: all
        CITestAppTests: [test]
        CITestAppUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - CITestApp
      targets:
        - CITestAppTests
        - CITestAppUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release